In [1]:
import numpy as np
from utils import sampler
from utils import graph_utils
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
# Generate data 
p = 5
edge_prob = .9
g = graph_utils.random_graph(p, edge_prob)
adj_mat = graph_utils.random_adj(g)
prec_mat = graph_utils.adj2prec(adj_mat)
int_data = graph_utils.sample_graph_int(g, adj_mat, [0, 1, 2, 3], [50, 50, 50, 50])

In [3]:
_, cheat_run1 = sampler.sample_dags(g, prec_mat, int_data, 100, 1, 1000)

{(2, 1)}
[0, 2, 1, 3, 4]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[[ 0.         -0.45619813 -0.86753697 -0.95364851 -0.8291383 ]
 [ 0.          0.          0.48305666  0.         -0.29721438]
 [ 0.          0.          0.          0.54705758 -0.52004586]
 [ 0.          0.          0.          0.          0.70773823]
 [ 0.          0.          0.          0.          0.        ]]
[0, 2, 1, 3, 4]
[0, 2, 1, 3, 4]
[0, 2, 1, 3, 4]
[[ 0.         -0.03010403 -1.08790651 -0.95364851 -0.8291383 ]
 [ 0.          0.          0.          0.         -0.29721438]
 [ 0.          0.39166426  0.          0.54705758 -0.52004586]
 [ 0.          0.          0.          0.          0.70773823]
 [ 0.          0.          0.          0.          0.        ]]
-1435.27536467 -1438.9389284
{(2, 1)}
[0, 2, 1, 3, 4]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[[ 0.         -0.45619813 -0.86753697 -0.95364851 -0.8291383 ]
 [ 0.          0.          0.48305666  0.         -0.29721438]
 [ 0.          0.  

[2, 0, 1, 3, 4]
[2, 0, 1, 3, 4]
[[ 0.          0.          0.         -0.95364851 -0.8291383 ]
 [-0.01893605  0.          0.81064814  0.         -0.29721438]
 [-0.4424545   0.          0.          0.54705758 -0.52004586]
 [ 0.          0.          0.          0.          0.70773823]
 [ 0.          0.          0.          0.          0.        ]]
-1435.21831785 -1460.35676873
{(0, 1)}
[0, 1, 2, 3, 4]
[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4]
[[ 0.          0.         -0.86753697 -0.95364851 -0.8291383 ]
 [-0.37761097  0.          0.48305666  0.         -0.29721438]
 [ 0.          0.          0.          0.54705758 -0.52004586]
 [ 0.          0.          0.          0.          0.70773823]
 [ 0.          0.          0.          0.          0.        ]]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[[ 0.         -0.45619813 -0.86753697 -0.95364851 -0.8291383 ]
 [ 0.          0.          0.48305666  0.         -0.29721438]
 [ 0.          0.          0.          0.54705758 -0.520045

[1, 2, 0, 3, 4]
[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4]
[[ 0.          0.         -0.86753697 -0.95364851 -0.8291383 ]
 [-0.37761097  0.          0.48305666  0.         -0.29721438]
 [ 0.          0.          0.          0.54705758 -0.52004586]
 [ 0.          0.          0.          0.          0.70773823]
 [ 0.          0.          0.          0.          0.        ]]
[1, 2, 0, 3, 4]
[2, 0, 1, 3, 4]
[2, 0, 1, 3, 4]
[[ 0.          0.          0.         -0.95364851 -0.8291383 ]
 [-0.01893605  0.          0.81064814  0.         -0.29721438]
 [-0.4424545   0.          0.          0.54705758 -0.52004586]
 [ 0.          0.          0.          0.          0.70773823]
 [ 0.          0.          0.          0.          0.        ]]
-1435.21831785 -1460.35676873
{(2, 0)}
[1, 2, 0, 3, 4]
[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4]
[[ 0.          0.         -0.86753697 -0.95364851 -0.8291383 ]
 [-0.37761097  0.          0.48305666  0.         -0.29721438]
 [ 0.          0.          

[0, 1, 2, 3, 4]
[[ 0.         -0.45619813 -0.86753697 -0.95364851 -0.8291383 ]
 [ 0.          0.          0.48305666  0.         -0.29721438]
 [ 0.          0.          0.          0.54705758 -0.52004586]
 [ 0.          0.          0.          0.          0.70773823]
 [ 0.          0.          0.          0.          0.        ]]
[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4]
[[ 0.          0.         -0.86753697 -0.95364851 -0.8291383 ]
 [-0.37761097  0.          0.48305666  0.         -0.29721438]
 [ 0.          0.          0.          0.54705758 -0.52004586]
 [ 0.          0.          0.          0.          0.70773823]
 [ 0.          0.          0.          0.          0.        ]]
-1435.27536467 -1435.21831785
{(2, 0)}
[1, 2, 0, 3, 4]
[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4]
[[ 0.          0.         -0.86753697 -0.95364851 -0.8291383 ]
 [-0.37761097  0.          0.48305666  0.         -0.29721438]
 [ 0.          0.          0.          0.54705758 -0.52004586]
 [ 0.       

-1435.21831785 -1460.35676873
{(2, 0)}
[1, 2, 0, 3, 4]
[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4]
[[ 0.          0.         -0.86753697 -0.95364851 -0.8291383 ]
 [-0.37761097  0.          0.48305666  0.         -0.29721438]
 [ 0.          0.          0.          0.54705758 -0.52004586]
 [ 0.          0.          0.          0.          0.70773823]
 [ 0.          0.          0.          0.          0.        ]]
[1, 2, 0, 3, 4]
[2, 0, 1, 3, 4]
[2, 0, 1, 3, 4]
[[ 0.          0.          0.         -0.95364851 -0.8291383 ]
 [-0.01893605  0.          0.81064814  0.         -0.29721438]
 [-0.4424545   0.          0.          0.54705758 -0.52004586]
 [ 0.          0.          0.          0.          0.70773823]
 [ 0.          0.          0.          0.          0.        ]]
-1435.21831785 -1460.35676873
{(2, 0)}
[1, 2, 0, 3, 4]
[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4]
[[ 0.          0.         -0.86753697 -0.95364851 -0.8291383 ]
 [-0.37761097  0.          0.48305666  0.         -

-1435.27536467 -1435.21831785
{(0, 1)}
[0, 1, 2, 3, 4]
[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4]
[[ 0.          0.         -0.86753697 -0.95364851 -0.8291383 ]
 [-0.37761097  0.          0.48305666  0.         -0.29721438]
 [ 0.          0.          0.          0.54705758 -0.52004586]
 [ 0.          0.          0.          0.          0.70773823]
 [ 0.          0.          0.          0.          0.        ]]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[[ 0.         -0.45619813 -0.86753697 -0.95364851 -0.8291383 ]
 [ 0.          0.          0.48305666  0.         -0.29721438]
 [ 0.          0.          0.          0.54705758 -0.52004586]
 [ 0.          0.          0.          0.          0.70773823]
 [ 0.          0.          0.          0.          0.        ]]
-1435.21831785 -1435.27536467
{(1, 0)}
[1, 0, 2, 3, 4]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[[ 0.         -0.45619813 -0.86753697 -0.95364851 -0.8291383 ]
 [ 0.          0.          0.48305666  0.         -

 [ 0.          0.          0.          0.          0.        ]]
[0, 2, 1, 3, 4]
[0, 2, 1, 3, 4]
[0, 2, 1, 3, 4]
[[ 0.         -0.03010403 -1.08790651 -0.95364851 -0.8291383 ]
 [ 0.          0.          0.          0.         -0.29721438]
 [ 0.          0.39166426  0.          0.54705758 -0.52004586]
 [ 0.          0.          0.          0.          0.70773823]
 [ 0.          0.          0.          0.          0.        ]]
-1435.27536467 -1438.9389284
{(2, 1)}
[0, 2, 1, 3, 4]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[[ 0.         -0.45619813 -0.86753697 -0.95364851 -0.8291383 ]
 [ 0.          0.          0.48305666  0.         -0.29721438]
 [ 0.          0.          0.          0.54705758 -0.52004586]
 [ 0.          0.          0.          0.          0.70773823]
 [ 0.          0.          0.          0.          0.        ]]
[0, 2, 1, 3, 4]
[0, 2, 1, 3, 4]
[0, 2, 1, 3, 4]
[[ 0.         -0.03010403 -1.08790651 -0.95364851 -0.8291383 ]
 [ 0.          0.          0.          0.  

-1435.21831785 -1460.35676873
{(2, 0)}
[1, 2, 0, 3, 4]
[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4]
[[ 0.          0.         -0.86753697 -0.95364851 -0.8291383 ]
 [-0.37761097  0.          0.48305666  0.         -0.29721438]
 [ 0.          0.          0.          0.54705758 -0.52004586]
 [ 0.          0.          0.          0.          0.70773823]
 [ 0.          0.          0.          0.          0.        ]]
[1, 2, 0, 3, 4]
[2, 0, 1, 3, 4]
[2, 0, 1, 3, 4]
[[ 0.          0.          0.         -0.95364851 -0.8291383 ]
 [-0.01893605  0.          0.81064814  0.         -0.29721438]
 [-0.4424545   0.          0.          0.54705758 -0.52004586]
 [ 0.          0.          0.          0.          0.70773823]
 [ 0.          0.          0.          0.          0.        ]]
-1435.21831785 -1460.35676873
{(2, 0)}
[1, 2, 0, 3, 4]
[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4]
[[ 0.          0.         -0.86753697 -0.95364851 -0.8291383 ]
 [-0.37761097  0.          0.48305666  0.         -

[2, 0, 1, 3, 4]
[[ 0.          0.          0.         -0.95364851 -0.8291383 ]
 [-0.01893605  0.          0.81064814  0.         -0.29721438]
 [-0.4424545   0.          0.          0.54705758 -0.52004586]
 [ 0.          0.          0.          0.          0.70773823]
 [ 0.          0.          0.          0.          0.        ]]
-1435.21831785 -1460.35676873
{(2, 0)}
[1, 2, 0, 3, 4]
[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4]
[[ 0.          0.         -0.86753697 -0.95364851 -0.8291383 ]
 [-0.37761097  0.          0.48305666  0.         -0.29721438]
 [ 0.          0.          0.          0.54705758 -0.52004586]
 [ 0.          0.          0.          0.          0.70773823]
 [ 0.          0.          0.          0.          0.        ]]
[1, 2, 0, 3, 4]
[2, 0, 1, 3, 4]
[2, 0, 1, 3, 4]
[[ 0.          0.          0.         -0.95364851 -0.8291383 ]
 [-0.01893605  0.          0.81064814  0.         -0.29721438]
 [-0.4424545   0.          0.          0.54705758 -0.52004586]
 [ 0.       

[0, 1, 2, 3, 4]
[[ 0.         -0.45619813 -0.86753697 -0.95364851 -0.8291383 ]
 [ 0.          0.          0.48305666  0.         -0.29721438]
 [ 0.          0.          0.          0.54705758 -0.52004586]
 [ 0.          0.          0.          0.          0.70773823]
 [ 0.          0.          0.          0.          0.        ]]
[0, 2, 1, 3, 4]
[0, 2, 1, 3, 4]
[0, 2, 1, 3, 4]
[[ 0.         -0.03010403 -1.08790651 -0.95364851 -0.8291383 ]
 [ 0.          0.          0.          0.         -0.29721438]
 [ 0.          0.39166426  0.          0.54705758 -0.52004586]
 [ 0.          0.          0.          0.          0.70773823]
 [ 0.          0.          0.          0.          0.        ]]
-1435.27536467 -1438.9389284
{(2, 1)}
[0, 2, 1, 3, 4]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[[ 0.         -0.45619813 -0.86753697 -0.95364851 -0.8291383 ]
 [ 0.          0.          0.48305666  0.         -0.29721438]
 [ 0.          0.          0.          0.54705758 -0.52004586]
 [ 0.        

[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4]
[[ 0.          0.         -0.86753697 -0.95364851 -0.8291383 ]
 [-0.37761097  0.          0.48305666  0.         -0.29721438]
 [ 0.          0.          0.          0.54705758 -0.52004586]
 [ 0.          0.          0.          0.          0.70773823]
 [ 0.          0.          0.          0.          0.        ]]
[1, 2, 0, 3, 4]
[2, 0, 1, 3, 4]
[2, 0, 1, 3, 4]
[[ 0.          0.          0.         -0.95364851 -0.8291383 ]
 [-0.01893605  0.          0.81064814  0.         -0.29721438]
 [-0.4424545   0.          0.          0.54705758 -0.52004586]
 [ 0.          0.          0.          0.          0.70773823]
 [ 0.          0.          0.          0.          0.        ]]
-1435.21831785 -1460.35676873
{(0, 1)}
[0, 1, 2, 3, 4]
[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4]
[[ 0.          0.         -0.86753697 -0.95364851 -0.8291383 ]
 [-0.37761097  0.          0.48305666  0.         -0.29721438]
 [ 0.          0.          0.          0.54705758 -0.520045

-1435.27536467 -1435.21831785
{(0, 1)}
[0, 1, 2, 3, 4]
[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4]
[[ 0.          0.         -0.86753697 -0.95364851 -0.8291383 ]
 [-0.37761097  0.          0.48305666  0.         -0.29721438]
 [ 0.          0.          0.          0.54705758 -0.52004586]
 [ 0.          0.          0.          0.          0.70773823]
 [ 0.          0.          0.          0.          0.        ]]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[[ 0.         -0.45619813 -0.86753697 -0.95364851 -0.8291383 ]
 [ 0.          0.          0.48305666  0.         -0.29721438]
 [ 0.          0.          0.          0.54705758 -0.52004586]
 [ 0.          0.          0.          0.          0.70773823]
 [ 0.          0.          0.          0.          0.        ]]
-1435.21831785 -1435.27536467
{(1, 0)}
[1, 0, 2, 3, 4]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[[ 0.         -0.45619813 -0.86753697 -0.95364851 -0.8291383 ]
 [ 0.          0.          0.48305666  0.         -

[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[[ 0.         -0.45619813 -0.86753697 -0.95364851 -0.8291383 ]
 [ 0.          0.          0.48305666  0.         -0.29721438]
 [ 0.          0.          0.          0.54705758 -0.52004586]
 [ 0.          0.          0.          0.          0.70773823]
 [ 0.          0.          0.          0.          0.        ]]
-1435.21831785 -1435.27536467
{(2, 1)}
[0, 2, 1, 3, 4]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[[ 0.         -0.45619813 -0.86753697 -0.95364851 -0.8291383 ]
 [ 0.          0.          0.48305666  0.         -0.29721438]
 [ 0.          0.          0.          0.54705758 -0.52004586]
 [ 0.          0.          0.          0.          0.70773823]
 [ 0.          0.          0.          0.          0.        ]]
[0, 2, 1, 3, 4]
[0, 2, 1, 3, 4]
[0, 2, 1, 3, 4]
[[ 0.         -0.03010403 -1.08790651 -0.95364851 -0.8291383 ]
 [ 0.          0.          0.          0.         -0.29721438]
 [ 0.          0.39166426  0.          0.54